# Generated by Django 4.1.3 on 2023-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_issue_assignee_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="description",
            field=models.CharField(default="default", max_length=10),
        ),
    ]
